load("//tools:bengine_rules.bzl", "bengine_cc_library")

package(default_visibility = ["//visibility:public"])

bengine_cc_library(
    name = "textures",
    hdrs = ["Texture.h"],
    deps = [
        "//core/containers:array",
        "//core/io/serialization:streams",
        "//core/io/serialization/compression",
        "//core/logging",
    ],
)
