load("//tools:bengine_rules.bzl", "bengine_cc_binary")

bengine_cc_binary(
    name = "model_compiler",
    srcs = [
        "ModelCompiler.cpp",
    ],
    deps = [
        "//Assets:importers",
        "//Core:containers",
        "//Core:io",
    ],
)
