load("//tools:bengine_rules.bzl", "bengine_cc_binary")

bengine_cc_binary(
    name = "compile",
    srcs = [
        "ModelCompiler.cpp",
    ],
    deps = [
        "//assets:importers",
        "//core:containers",
        "//core:io",
    ],
)
