load("//tools:bengine_rules.bzl", "bengine_cc_library")

bengine_cc_library(
    name = "catch2_test_main",
    srcs = [
        "catch2_test_main.cpp",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@catch2",
    ],
)
