load("//tools:bengine_rules.bzl", "bengine_cc_library")

package(default_visibility = ["//visibility:public"])

bengine_cc_library(
    name = "resources",
    hdrs = [
        "GPUMaterial.h",
        "GPUMesh.h",
        "GPUTexture.h",
    ],
    deps = ["//renderer/backends/vulkan"],
)
